title: Sparti
description: IT-konsulter med omtanke, måttfullhet och tillit som ledstjärnor.
orgnr: 559139-4290

footer:
  navigation:
    - url: /arbetskamrater.html
    - url: /handbok.html
    - url: /tillganglighet.html

contact:
  mail: kontakt@sparti.se
  phone:
    href: "+46735318592"
    text: "073 531 85 92"

copyright:
  year: 2020
  org: Sparti AB

collections:
  people:
    output: false

defaults:
  - scope:
      path: ""
    values:
      locale: sv_SE
      image:
        path: /assets/images/SPARTI_logo_1200x1200.jpg
        width: 1200
        height: 1200

google_analytics:
url: "https://www.sparti.se" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

remote_theme: turbotobbe/jekyll-theme-sparti
theme: jekyll-theme-sparti
plugins:
  - jekyll-seo-tag

exclude:
  - Dockerfile
  - read_csv.rb
  - README.md
  - Gemfile*
