title: Sparti
description: Omtanke Tillit Måttfullhet
orgnr: 559139-4290

footer:
  navigation:
    - url: /vi-ar-sparti.html
#    - url: /handbok.html
#    - url: /tillganglighet.html

contact:
  mail: info@sparti.se
  phone:
    href: "+46735318592"
    text: "073 531 85 92"

copyright:
  year: 2020
  org: Sparti AB

collections:
  people:
    output: false

defaults:
  - scope:
      path: ""
    values:
      locale: sv_SE
      image:
        path: /assets/images/SPARTI_logo_1200x1200.jpg
        width: 1200
        height: 1200

google_analytics:
url: "https://www.sparti.se" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

remote_theme: https://github.com/turbotobbe/jekyll-theme-sparti
#remote_theme: turbotobbe/jekyll-theme-sparti
theme: jekyll-theme-sparti
plugins:
  - jekyll-seo-tag

exclude:
  - about.md
  - build.sh
  - CNAME
  - design.md
  - Dockerfile
  - Gemfile*
  - handbok.md
  - jekyll.sh
  - read_csv.rb
  - README.md
  - tillganglighet.md
  - wcag.csv
